version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq-mgmt
    ports:
      - "5672:5672"
      - "15672:15672"

  ui:
    build: ./ui
    ports:
      - "5000:5000"

  driver:
    build: ./microservices/driver
    container_name: driver_microservice
    ports:
      - "5003:5000"
    environment:
      - dbURL=mysql+mysqlconnector://admin:rootroot@db-savood.c0hav88yk9mq.us-east-1.rds.amazonaws.com:3306/driver

  restaurant:
    build: ./microservices/restaurant
    container_name: restaurant_microservice
    ports:
      - "5001:5000"
    environment:
      - dbURL=mysql+mysqlconnector://admin:rootroot@db-savood.c0hav88yk9mq.us-east-1.rds.amazonaws.com:3306/restaurant

  foodbank:
    build: ./microservices/foodbank
    container_name: foodbank_microservice
    ports:
      - "5002:5000"
    environment:
      - dbURL=mysql+mysqlconnector://admin:rootroot@db-savood.c0hav88yk9mq.us-east-1.rds.amazonaws.com:3306/foodbank

  order-management:
    build: ./microservices/order-management
    container_name: order-management_microservice
    ports:
      - "5004:5000"
    environment:
      - dbURL=mysql+mysqlconnector://admin:rootroot@db-savood.c0hav88yk9mq.us-east-1.rds.amazonaws.com:3306/order_database

  notification:
    build: ./microservices/notification
    container_name: notification_microservice
    ports:
      - "5005:5000"
    environment:
      - RABBITMQ_HOST=rabbitmq

  user:
    build: ./microservices/user
    container_name: user_microservice
    ports:
      - "5006:5000"
    environment:
      - dbURL=mysql+mysqlconnector://admin:rootroot@db-savood.c0hav88yk9mq.us-east-1.rds.amazonaws.com:3306/user
  
  post-surplus-food:
    build: ./microservices/post-surplus-food
    container_name: post_surplus_food_microservice
    ports:
      - "5007:5000"
  
  place-order:
    build: ./microservices/place-order
    container_name: place_order_microservice
    ports:
      - "5008:5000"

  accept-order:
    build: ./microservices/accept-order
    container_name: accept_order_microservice
    ports:
      - "5009:5000"